MH-27:
akupreychik/mentor_helper pull request #34
Opened 2022-10-05 19:00 UTC by mckeydonelly

- https://www.notion.so/akupreychik/Create-user-controller-2303691750b14e6cb9438b886e709022
- https://www.notion.so/akupreychik/UserController-810f793d21f1444bb1cb9e6073c58c9b

1. Adding UserController
2. Simple change bot initializer to spring-starter

2022-10-05 21:13 UTC, akupreychik requested changes
поправь моменты + не увидел тестов на сервис и репозиторий

2022-10-05 21:13 UTC, akupreychik commented on src/main/java/com/ua/javarush/mentor/bot/MentorHelperBot.java
> -    @Bean
зачем это удалять? сейчас бот работает в качестве эхо.

2022-10-05 21:13 UTC, akupreychik commented on src/main/java/com/ua/javarush/mentor/controller/UserController.java
> +    public ResponseEntity<List<UserDTO>> getAllUsersPageable(@RequestBody UserPageableRequest userPageableRequest) {
параметр страницы указывается через @RequestParam(value = "page", required = false, defaultValue = "0") int page

2022-10-05 21:13 UTC, akupreychik commented on src/main/java/com/ua/javarush/mentor/controller/UserController.java
> +    public ResponseEntity<UserDTO> createNewRole(@RequestBody UserRequest userRequest) {
переименовать в UserCreateCommand и перенести в пакет src/main/java/com/ua/javarush/mentor/command

2022-10-05 21:13 UTC, akupreychik commented on src/main/java/com/ua/javarush/mentor/controller/UserController.java
> +        return new ResponseEntity<>(userService.changePermission(userPermissionRequest.getUserId(), userPermissionRequest.getRoleId()), HttpStatus.OK);
можно сделать чтобы метод принимал не long, long а userPermissionRequest.
и потом уже в сервисе вытянуть данные которые тебе будут нужны

2022-10-05 21:13 UTC, akupreychik commented on src/main/java/com/ua/javarush/mentor/controller/user/UserPageableRequest.java
> +}
этот класс лишний

2022-10-05 21:13 UTC, akupreychik commented on src/main/java/com/ua/javarush/mentor/controller/user/UserPermissionRequest.java
> +package com.ua.javarush.mentor.controller.user;
тоже переименовать в ...Command и перенести

2022-10-05 21:13 UTC, akupreychik commented on src/main/java/com/ua/javarush/mentor/controller/user/UserRequest.java
> +package com.ua.javarush.mentor.controller.user;
тоже переименовать в ...Command и перенести

2022-10-05 21:13 UTC, akupreychik commented on src/main/java/com/ua/javarush/mentor/mapper/UserMapper.java
> +    @Mapping(target = "roleId", expression = "java(roleRepository.findById(userRequest.getRoleId()).get())")
а что будет если при выполнение этого маппинга упадет ошибка?

2022-10-05 21:13 UTC, akupreychik commented on src/main/java/com/ua/javarush/mentor/persist/model/User.java
> +@Table(name = "`USER`")
кажется это лишнее тут

2022-10-05 21:13 UTC, akupreychik commented on src/main/java/com/ua/javarush/mentor/persist/model/User.java
> +    @Column(name = "TELEGRAM_ID", unique = true)
если убираешь эту настройку тут, то нужно подправить этот момент и в миграции

2022-10-05 21:13 UTC, akupreychik commented on src/main/java/com/ua/javarush/mentor/services/UserService.java
> +    List<UserDTO> getAllUsers(Integer page);
эти два запроса можно объединить, и сделать параметр страницы не обязательный - тогда получится на один метод меньше

2022-10-05 21:13 UTC, akupreychik commented on src/main/java/com/ua/javarush/mentor/services/UserService.java
> +    UserDTO create(UserRequest userRequest);
добавить createUser для одинакового нэйминга

2022-10-05 21:13 UTC, akupreychik commented on src/main/java/com/ua/javarush/mentor/services/impl/UserServiceImpl.java
> +    private Integer PAGE_SIZE;
изменить регистр - должен быть camelCase

2022-10-05 21:13 UTC, akupreychik commented on src/main/java/com/ua/javarush/mentor/services/impl/UserServiceImpl.java
> +        newUser.setRegisteredAt(new Timestamp(System.currentTimeMillis()));
можно ли перенести это в маппинг?

2022-10-05 21:13 UTC, akupreychik commented on src/main/java/com/ua/javarush/mentor/services/impl/UserServiceImpl.java
> +public class UserServiceImpl implements UserService {
авто форматирование по всему файлу

2022-10-05 21:17 UTC, akupreychik commented on src/main/resources/application.properties
> +user.pageSize=5
это можно использовать для всего проекта, получится default.pageSize

2022-10-05 21:20 UTC, akupreychik commented on src/main/java/com/ua/javarush/mentor/persist/model/User.java
>  @Data
аннотацию дату лучше заменить на сборку @Getter
@Setter
@ToString
@RequiredArgsConstructor

2022-10-05 21:20 UTC, akupreychik commented on src/main/java/com/ua/javarush/mentor/persist/model/User.java
>  @Data
+ добавить hashCode + equals от hibernate - 

```
@Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || Hibernate.getClass(this) != Hibernate.getClass(o)) return false;
        User user = (User) o;
        return id != null && Objects.equals(id, user.id);
    }

```

 ```
   @Override
    public int hashCode() {
        return getClass().hashCode();
    }
```

2022-10-06 05:40 UTC, mckeydonelly commented on src/main/resources/application.properties
> +user.pageSize=5
done

2022-10-06 06:14 UTC, mckeydonelly commented on src/main/java/com/ua/javarush/mentor/services/impl/UserServiceImpl.java
> +    }
что-то понял, добавил

2022-10-06 06:21 UTC, mckeydonelly commented on src/main/resources/db/changelog/db.changelog-master.yaml
> -                    nullable: false
done

2022-10-06 06:22 UTC, mckeydonelly commented on src/main/java/com/ua/javarush/mentor/services/impl/UserServiceImpl.java
> +            throw GeneralExceptionUtils.createGeneralException("Didn't found user", HttpStatus.NOT_FOUND, Error.USER_NOT_FOUND);
done

2022-10-06 06:27 UTC, mckeydonelly commented on src/main/java/com/ua/javarush/mentor/services/impl/UserServiceImpl.java
> +            log.warn("Didn't found user with id {}", id);
done

2022-10-06 06:30 UTC, mckeydonelly commented on src/main/java/com/ua/javarush/mentor/services/impl/UserServiceImpl.java
> +        log.info("Response user: {}", optionalUser.get());
done

2022-10-06 06:42 UTC, mckeydonelly commented on src/main/java/com/ua/javarush/mentor/services/impl/UserServiceImpl.java
> +        }
done, но как логировать ошибки? внутри GeneralExceptionUtils?

2022-10-06 06:43 UTC, mckeydonelly commented on src/main/java/com/ua/javarush/mentor/services/impl/UserServiceImpl.java
> +public class UserServiceImpl implements UserService {
done

2022-10-06 06:52 UTC, mckeydonelly commented on src/main/java/com/ua/javarush/mentor/services/impl/UserServiceImpl.java
> +        System.out.println(newUser);
yep

2022-10-06 06:54 UTC, mckeydonelly commented on src/main/java/com/ua/javarush/mentor/services/impl/UserServiceImpl.java
> +        newUser.setRegisteredAt(new Timestamp(System.currentTimeMillis()));
done, только не понял как импорт в expression сделать, прописал полный путь до класса

2022-10-06 06:56 UTC, mckeydonelly commented on src/main/java/com/ua/javarush/mentor/services/UserService.java
> +    UserDTO create(UserRequest userRequest);
done

2022-10-06 07:13 UTC, mckeydonelly commented on src/main/java/com/ua/javarush/mentor/services/UserService.java
> +    List<UserDTO> getAllUsers(Integer page);
не очень понял о чем ты, поправил на глаз

2022-10-06 07:15 UTC, mckeydonelly commented on src/main/java/com/ua/javarush/mentor/persist/model/User.java
> +@Table(name = "`USER`")
без нее не получается https://stackoverflow.com/questions/9035971/error-syntax-error-at-or-near-user

2022-10-06 20:07 UTC, mckeydonelly commented on src/main/java/com/ua/javarush/mentor/mapper/UserMapper.java
> +    @Mapping(target = "roleId", expression = "java(roleRepository.findById(userRequest.getRoleId()).get())")
разобрались в личке, поправил

2022-10-06 20:09 UTC, mckeydonelly commented on src/main/java/com/ua/javarush/mentor/controller/user/UserRequest.java
> +package com.ua.javarush.mentor.controller.user;
done

2022-10-06 20:09 UTC, mckeydonelly commented on src/main/java/com/ua/javarush/mentor/controller/user/UserPermissionRequest.java
> +package com.ua.javarush.mentor.controller.user;
done

2022-10-06 20:10 UTC, mckeydonelly commented on src/main/java/com/ua/javarush/mentor/controller/UserController.java
> +        return new ResponseEntity<>(userService.changePermission(userPermissionRequest.getUserId(), userPermissionRequest.getRoleId()), HttpStatus.OK);
done

2022-10-06 20:10 UTC, mckeydonelly commented on src/main/java/com/ua/javarush/mentor/controller/UserController.java
> +    public ResponseEntity<UserDTO> createNewRole(@RequestBody UserRequest userRequest) {
done

2022-10-06 20:11 UTC, mckeydonelly commented on src/main/java/com/ua/javarush/mentor/controller/UserController.java
> +    public ResponseEntity<List<UserDTO>> getAllUsersPageable(@RequestBody UserPageableRequest userPageableRequest) {
done

2022-10-06 20:15 UTC, mckeydonelly commented on src/main/java/com/ua/javarush/mentor/bot/MentorHelperBot.java
> -    @Bean
вернул назад

2022-10-06 22:38 UTC, akupreychik approved these changes

2022-10-06 22:38 UTC, merged